/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as OrdenesRouteImport } from './routes/ordenes'
import { Route as MovimientosRouteImport } from './routes/movimientos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FacturasRouteImport } from './routes/facturas'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminLimpiarDatosRouteImport } from './routes/admin.limpiar-datos'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdenesRoute = OrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimientosRoute = MovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasRoute = FacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLimpiarDatosRoute = AdminLimpiarDatosRouteImport.update({
  id: '/admin/limpiar-datos',
  path: '/admin/limpiar-datos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/facturas': typeof FacturasRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/ordenes': typeof OrdenesRoute
  '/productos': typeof ProductosRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/soporte': typeof SoporteRoute
  '/usuarios': typeof UsuariosRoute
  '/admin/limpiar-datos': typeof AdminLimpiarDatosRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/facturas': typeof FacturasRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/ordenes': typeof OrdenesRoute
  '/productos': typeof ProductosRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/soporte': typeof SoporteRoute
  '/usuarios': typeof UsuariosRoute
  '/admin/limpiar-datos': typeof AdminLimpiarDatosRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/facturas': typeof FacturasRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/ordenes': typeof OrdenesRoute
  '/productos': typeof ProductosRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/soporte': typeof SoporteRoute
  '/usuarios': typeof UsuariosRoute
  '/admin/limpiar-datos': typeof AdminLimpiarDatosRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/configuracion'
    | '/facturas'
    | '/login'
    | '/movimientos'
    | '/ordenes'
    | '/productos'
    | '/recuperar'
    | '/registro'
    | '/reportes'
    | '/soporte'
    | '/usuarios'
    | '/admin/limpiar-datos'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/configuracion'
    | '/facturas'
    | '/login'
    | '/movimientos'
    | '/ordenes'
    | '/productos'
    | '/recuperar'
    | '/registro'
    | '/reportes'
    | '/soporte'
    | '/usuarios'
    | '/admin/limpiar-datos'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/configuracion'
    | '/facturas'
    | '/login'
    | '/movimientos'
    | '/ordenes'
    | '/productos'
    | '/recuperar'
    | '/registro'
    | '/reportes'
    | '/soporte'
    | '/usuarios'
    | '/admin/limpiar-datos'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  FacturasRoute: typeof FacturasRoute
  LoginRoute: typeof LoginRoute
  MovimientosRoute: typeof MovimientosRoute
  OrdenesRoute: typeof OrdenesRoute
  ProductosRoute: typeof ProductosRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  ReportesRoute: typeof ReportesRoute
  SoporteRoute: typeof SoporteRoute
  UsuariosRoute: typeof UsuariosRoute
  AdminLimpiarDatosRoute: typeof AdminLimpiarDatosRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordenes': {
      id: '/ordenes'
      path: '/ordenes'
      fullPath: '/ordenes'
      preLoaderRoute: typeof OrdenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimientos': {
      id: '/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof MovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas': {
      id: '/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof FacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/limpiar-datos': {
      id: '/admin/limpiar-datos'
      path: '/admin/limpiar-datos'
      fullPath: '/admin/limpiar-datos'
      preLoaderRoute: typeof AdminLimpiarDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  FacturasRoute: FacturasRoute,
  LoginRoute: LoginRoute,
  MovimientosRoute: MovimientosRoute,
  OrdenesRoute: OrdenesRoute,
  ProductosRoute: ProductosRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  ReportesRoute: ReportesRoute,
  SoporteRoute: SoporteRoute,
  UsuariosRoute: UsuariosRoute,
  AdminLimpiarDatosRoute: AdminLimpiarDatosRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
